name: Build CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install
      run: |
        npm ci
      env:
        CI: true
    - name: lint
      run: |
        npm run lint
      env:
        CI: true
    - name: unit test
      run: |
        npm run test:unit
      env:
        CI: true
    - name: Log into registry
      run: echo "${{ secrets.sa }}" | docker login docker.pkg.github.com -u ${{ github.sa_name }} --password-stdin
    - name: Build image
      run: docker build . --file Dockerfile --tag maintain
    - name: Push image
      run: |
          IMAGE_ID=bcrentities-docker-local.artifacts.developer.gov.bc.ca/maintain
          VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

